### ISSUE TITLE
UrlError, is data still available somewhere?

### ISSUE THREAD

**Issue by mathurinm** [ramp-kits/mars_craters#69]
Hi team,
Thanks for all the efforts in putting up this great RAMP. I wanted to use it but it seems that the data is no longer available. Is there an archive somewhere?
Thanks a lot
Mathurin

**Comment by agramfort** [comment]
here is what I have

https://www.dropbox.com/s/94s3stuzn1xr9ho/mars_crater_data.zip?dl=0

**Comment by mathurinm** [comment]
Thanks Alex
